spring.application.name=qi-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/qi_db
spring.datasource.username=postgres
spring.datasource.password=Arun#123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

# AI Configuration
ai.provider=builtin
ai.gemini.api-key=